# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# ------
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.3-cli

pipelines:
    branches:
        master:
            - step:
                name:   UnitTest
                script:
                    - apt-get update && apt-get install -y unzip ssh
                    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                    - php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
                    - php composer-setup.php
                    - php -r "unlink('composer-setup.php');"
                    - php composer.phar install
                    - cp phpunit.xml.dist phpunit.xml
                    - php vendor/bin/phpunit -c phpunit.xml